version: 1
root: .
main_path: "./delivery"
tmp_path: ./tmp
build_name: runner-build
build_args:
run_args:
build_log: runner-build-errors.log
valid_ext: .go
build_delay: 500ms
colors: true
log_color_main: cyan
log_color_build: yellow
log_color_runner: green
log_color_watcher: magenta
log_color_app:
debug: true